allowlist:
  - name: "rt/chatter"
    type: "std_msgs::msg::dds_::String_"
  - name: "rt/odom"
    type: "nav_msgs::msg::dds_::Odometry_"
  - name: "rt/rosout"
    type: "rcl_interfaces::msg::dds_::Log_"
  - name: "rt/scan"
    type: "sensor_msgs::msg::dds_::LaserScan_"
  - name: "rt/tf"
    type: "tf2_msgs::msg::dds_::TFMessage_"
  - name: "rt/map"
    type: "nav_msgs::msg::dds_::OccupancyGrid_"
  - name: "rt/map_metadata"
    type: "nav_msgs::msg::dds_::MapMetaData_"
  - name: "rt/laser/scan"
    type: "sensor_msgs::msg::dds_::LaserScan_"
  - name: "rt/goal_pose"
    type: "geometry_msgs::msg::dds_::PoseStamped_"

echo_participant:
  type: echo

external_partipant:
  type: "local-discovery-server"
  id: 200

  listening-addresses:
    - domain: "ds"  # using hostname instead of Husarnet IPv6 addr
      port: 11811
      transport: "udp"
      
