
# Quick Start
# $ xhost local:root
# $ docker compose up

services:

  rviz:
    image: husarion/rviz2
    runtime: nvidia
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../rviz/panther_nav2.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  panther-gazebo:
    image: husarion/panther-gazebo:galactic-latest
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    command: >
      ros2 launch panther_gazebo panther.launch.py 
      use_gpu:=true

  nav2:
    image: husarion/nav2:galactic-latest
    volumes:
      - ../nav2_config/nav2_params.yaml:/app/ros2_ws/src/husarion_nav2/config/nav2_params.yaml
      - ../nav2_config/slam_toolbox.yaml:/app/ros2_ws/src/husarion_nav2/config/slam_toolbox.yaml
    command: ros2 launch husarion_nav2 bringup_both.launch.py